### ISSUE TITLE
Hide Disqus form on second click on icon

### ISSUE THREAD

**Issue by Globulopolis** [tsi/inlineDisqussions#1]
Hi! I know it is not hard to implement. On the first click we show the disqus form. But for hide form we need to click another icon. Can you implement - if we click on icon and disqus form already showed so hide her.

**Comment by n0nick** [comment]
:+1: 
Second click on the count icon is easy enough.
I think clicking anywhere outside the comment box should close it - that's what Medium are doing.

**Comment by tsi** [comment]
Thanks! I've implemented both - second click on the icon or a click anywhere outside.
