### ISSUE TITLE
Installing inlineDisqussions

### ISSUE THREAD

**Issue by larsenaj** [tsi/inlineDisqussions#14]
Hi Tsachi, 

This is amazing, thanks so much for creating it.  

However, as a newbie I'm having a hard time installing this on my Wordpress site and was hoping you could expand a bit on your instructions.  

I've downloaded the zip and uploaded all the files to my main WP-Admin folder.  Here are my questions:
1.  Precisely where do I place the following code (what file, where in the code)?

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

<script src="inlineDisqussions.js"></script>

1.  Does the following code go into my theme's custom CSS? 

<link rel="stylesheet" type="text/css" href="inlineDisqussions.css" />
1.  On the blog Post that I want to implement the annotations, how exactly do I use your last bit of code (my Disqus shortname is larsentoylab)?

<script>
  disqus_shortname = 'your_disqus_shortname';
  jQuery(document).ready(function() {
    jQuery("p").inlineDisqussions();
  });
</script>

**Comment by kevinweber** [comment]
Hi larsenaj,
I had similar problems, so I've already published an official WordPress plugin that does the whole job for you: http://wordpress.org/plugins/inline-comments/

Best regards,
Kevin

**Comment by tsi** [comment]
Yep, that would be the way to use this with WP, thanks @kevinweber.

**Comment by larsenaj** [comment]
Thanks Kevin!

On Sun, Jun 8, 2014 at 2:44 PM, Tsachi Shlidor notifications@github.com
wrote:

> Closed #14 https://github.com/tsi/inlineDisqussions/issues/14.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tsi/inlineDisqussions/issues/14#event-129169204.

## 

_Alex Larsen_
Co Founder, Larsen Toy Lab http://larsentoylab.com/
(W) 203-349-5070
(M) 203-253-4911
