### ISSUE TITLE
multple feeds on existing disqus

### ISSUE THREAD

**Issue by darylgeary** [tsi/inlineDisqussions#21]
Thank you for addressing this issue.

I have installed your conclusion which works perfectly well.

Can I adapt it to fit the existing disqus, and use your multiple feeds?

Many thanks
Daryl

**Comment by tsi** [comment]
Never tried adding this to an existing disqus, but it should be possible, see the paragraph where it says "Can we still have a main comment thread at the bottom?" on the [demo](http://tsi.github.io/inlineDisqussions/)

**Comment by darylgeary** [comment]
Thank you for you reply.

All works fine.

What I'm really trying to achieve is being able to create multiple threads within existing disqus. You have achieved this with a unique thread per <p>.

**Comment by tsi** [comment]
Yes but I also have a main comment thread at the bottom, that would (hopefully) be your current disqus single thread while you'll be able to attach new unique threads to `<p>`s (or any other element)

**Comment by darylgeary** [comment]
Thanks tsi
