### ISSUE TITLE
Error: 01:49:14.832 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. 

### ISSUE THREAD

**Issue by IAmAlfred** [tsi/inlineDisqussions#26]
I've done everything in the instructions, included all js, css, jquery and called whatever was supposed to be called according to the guide.

I then removed the following from my page: `<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>` and kept the correct version: `<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>`

This lead to an error in the console: 

ReferenceError: jQuery is not defined inlineDisqussions.js:291:0

And I haven't even touched any code in the .js file, any solutions?

**Comment by tsi** [comment]
Any chance you're calling jQuery _after_ calling inlineDisqussions ?

**Comment by IAmAlfred** [comment]
Nope; http://i.imgur.com/eJ8fzb1.png and this is the result I'm receiving: http://i.imgur.com/NQGCnNp.png

**Comment by tsi** [comment]
You should not be calling JS files directly from your file system (e.g. file://), I think that is what's causing your issues. You should have a server, even if it's a local one, that answer these requests.
For testing, you can call inlineDisqussions using:
`<script src="https://raw.githubusercontent.com/tsi/inlineDisqussions/master/inlineDisqussions.js"></script>`

**Comment by IAmAlfred** [comment]
I've loaded the js files from my webhost and still the same result. This is the real problem: http://i.imgur.com/v7xV6o8.png

So perhaps the solution lies in me trying different JQuery versions, I'll try it now and I'll let you know how it goes.

**Comment by IAmAlfred** [comment]
Well I got rid of the error message here: http://i.imgur.com/v7xV6o8.png by simply using the following:
$.ajaxPrefilter(function( options, originalOptions, jqXHR ) {
    options.async = true;
});

But Disqus is still not loading, here are my disqus settings:

  disqus_shortname = 'StoriesRUs';
  jQuery(document).ready(function() {
    jQuery("p").inlineDisqussions({
  identifier: 'disqussion',
  displayCount: true,
  highlighted: true,
  position: 'left',
  background: 'white',
  maxWidth: 9999
});
  });

**Comment by IAmAlfred** [comment]
Anyone have any ideas?

**Comment by tsi** [comment]
Can you share the page? can we see it? I'm not sure the error and the disqus issue are even related.

**Comment by IAmAlfred** [comment]
Website: http://sterlingsanya.esy.es/home/gitty.html
Here's the code: http://pastebin.com/ZPU9rqpN  

UPDATE: Oh wow, it appears that disqus loads on a server, interesting.(I'm inexperienced sorry!)  HOWEVER, it only shows signs of loading, the actual disqus comment box doesn't load due to the error "unable to load disqus" (which didn't show previously on my desktop).

**Comment by IAmAlfred** [comment]
Does anyone know anything about this problem?

**Comment by tsi** [comment]
Looks like a problem with your disquss account, if I load [this](http://codepen.io/beshur/pen/klrKz) codepen (which works fine) with _your_ `disqus_shortname` it returns an error.

**Comment by IAmAlfred** [comment]
Awesome, thank you Tsi ^.^ #GreeceFTW
