### ISSUE TITLE
Comments appear on the bottom of the page

### ISSUE THREAD

**Issue by cutterkom** [tsi/inlineDisqussions#3]
Hey! 

I have an issue with positioning the comments. They appear on the bottom the page under the content, when using the default selector "p". 
![bildschirmfoto 2013-10-29 um 16 05 59](https://f.cloud.github.com/assets/4574033/1428997/a9f028c6-40ab-11e3-955d-a8d92893871b.png)

If I use p.post-content, nothing happens. 

I am using WordPress, my structure is the following: 

```
<section class="post-content">
            <h2><a href="<?php the_permalink() ?>" rel="bookmark" title="<?php the_title(); ?>"><?php the_title(); ?>adsf</a></h2>
            <p class="dis"><?php echo the_content(); ?></p>
  </section>
```

So I guess, I am using a wrong selector, but I can't figure out the right one. 

Thanks for your help!

**Comment by tsi** [comment]
Two different issues:
1. selector - should be either 'p.dis' or 'section.post-content', you don't have any 'p.post-content'.
2. positioning - did you include the CSS?

**Comment by kevinweber** [comment]
Hi @cutterkom,
you should consider Inline Comments for your WordPress site. This plugin brings inlineDisqussions to WordPress and is available on WordPress.org for free: www.kevinw.de/inline-comments

Best regards,
Kevin
