### ISSUE TITLE
Is working for the top texts only

### ISSUE THREAD

**Issue by titombo** [tsi/inlineDisqussions#4]
Try this text as an example:
http://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm

I've copy and paste that in my solution.

Only the top one's work, the rest don't.
It gives the error output:

Error 503 Service Unavailable

Service Unavailable

Guru Meditation:

XID: 1901407802

Varnish cache server

**Comment by tsi** [comment]
I don't see you calling inlineDisqussions on that page.

**Comment by titombo** [comment]
Sorry, I mean, I just got this HTML code, copied and paste in my solution and used your code example for comments in each paraghraph.

**Comment by tsi** [comment]
Sorry mate, I really can't help you this way.
What is "this HTML code"?
What is "my solution"?
What is "your code example"?

**Comment by titombo** [comment]
Man, sorry, I just fixed it, it was due the padding it needs, you need to let to the page on the right-side or left-side, it doesn't override the text. Works like a charm, you made a good job!! :)
I just used your own page as an example.

Using the CSS

<style type="text/css">
    
#container {
    max-width: 960px;
    min-height: 595px;
}
.inner {
    margin: 0 auto;
    width: 620px;
}
</style>

and HTML:

div id="container">
div class="inner" >

/div>
/div>
Btw I am a big fan of Israel, it has an amazing educational system!

**Comment by tsi** [comment]
Awesome, I'm glad it works.
