### ISSUE TITLE
Sugestion: Request the comments only when is clicked

### ISSUE THREAD

**Issue by titombo** [tsi/inlineDisqussions#5]
Thanks to your js API I made this website:
http://constituicaocomentada.somee.com/

It is the constitution of my country, it would make easier for lawyers to study it, since there is many different opinions on each part of the text.
But the problem I am facing is with performance, it is downloading too many files at once.
Maybe would be a good solution to download it on-demand, only when user clicks on the number to check the comments.
Do you think that is possible ?

**Comment by tsi** [comment]
See my comment on #6, the problem is probably caused by the script that fetches the comments count from Disqus.
